env:
  global:
    - DATABASE_URL=mysql://root@127.0.0.1:3306/fireping_test
    - RRDCACHED_TEST=127.0.0.1:42217
    # Symfony's PHPUnit bridge provides a modified version of PHPUnit. The modified PHPUnit is
    # written to a directory that can be configured by the SYMFONY_PHPUNIT_DIR env var, or in
    # the same directory as the simple-phpunit if it is not provided. It's also possible to set
    # this env var in the phpunit.xml.dist file.
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=max[direct]=0

language: php
os: linux

# Start mysql service
services:
  - redis
  - mysql
  - docker

# Cache composer packages so "composer install" is faster
cache:
  directories:
    # Cache composer packages so "composer install" is faster.
    - $HOME/.composer/cache/files
    # Cache the directory where Symfony stores its slightly modified version of PHPUnit.
    - ./bin/.phpunit
    # Cache the Symfony binary's directory so that it does not have to be reinstalled.
    - $HOME/.symfony

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client

jobs:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: master
    - php: 7.4
      env: COVERAGE=true
    - php: 7.3
  allow_failures:
    - php: master

before_install:
  - export PATH="$HOME/.symfony/bin:$PATH"
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi
  - if symfony self:version; then symfony self:update --yes ; else wget https://get.symfony.com/cli/installer -O - | bash ; fi
  # Install RRDTool
  - sudo apt-get -qq update
  - sudo apt-get install -y librrd-dev rrdtool
  - composer self-update
  - mkdir build
  - pecl install rrd
  - mysql -e 'CREATE DATABASE fireping_test;'
  # Setup the rrdcached container.
  # We are forcing the PUID and PGID of the rrdcached daemon to the same UID/GID of the host so that we can pretend it's
  # A locally running rrdcached, which for instance RrdCachedStorage assumes it to be.
  - HOST_USERID=$(id -u $(whoami))
  - HOST_GROUPID=$(id -g $(whoami))
  - docker run -d -p 127.0.0.1:42217:42217 --name rrdcached -v /tmp/fireping/rrd:/data/db -e TZ="Europe/Paris" -e PUID=$HOST_USERID -e PGID=$HOST_GROUPID crazymax/rrdcached

install:
  - composer -n install --prefer-dist

script:
  - php bin/console cache:warmup --env=slave
  - vendor/bin/phpunit
  - composer phpstan
  # This checks that the YAML config files contain no syntax errors.
  - ./bin/console lint:yaml config --parse-tags
  # This checks that the Twig template files contain no syntax errors.
  - ./bin/console lint:twig templates --env=prod
  # This checks that the XLIFF translations contain no syntax errors.
  - ./bin/console lint:xliff translations
  # This checks that arguments injected into services match type declarations.
  - ./bin/console lint:container
  # This checks that the application doesn't use dependencies with known security vulnerabilities.
  - symfony check:security
  # This checks that Doctrine's mapping configurations are valid.
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - composer validate --strict

after_script:
  - |
    if [[ $COVERAGE == true && $TRAVIS_BRANCH == "master" ]]; then
      ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.0/php-coveralls.phar
      php php-coveralls.phar --verbose
    fi

after_failure: "cat var/log/*.log"

# After a build, send email notification with the build results
notifications:
  email: jimmy.cleuren@gmail.com
  slack:
    secure: mueCh2GiVAIoqw21iOlxdyij3dmAkalYIOQphvruZTlxprKL4UKFJp4oqwBrvuEHd7Y0cSOnO0Sx5dZ6hDSn7FbzMK96zoJIiuh6Cxe2AQYWTJ+NXfmtGWRR+fSIit+1jz4iadSotzYdlE4nTZovPV3ZHaSuX1VWfdedCEs+tbXapy/uVxNWiAcnY76c+l28notpnCxWZz8Ak32+yaZpGwVx6NczE7okF4cEyDIwCQO+AZWlU2PW2sVxfKTNbqFSj8J71Af1l4abmB3UR0ZYCVFaXVoANtEp2RR8IVSTT1eCbo1Ns4EYVI2IwP5Gxb1cs9q71okMtaGaeOM4OB7YHp727AHzAf+u9wAhDZi6Php02cyMjysNpprAqbwbTxPm2Rmy9vsoKmJJZHnvYfcvF5+nh1AQLj6sUkCqs+nWTSpAsZ0YEW8HwHDra/CHfPOTbl/CWgqPCyTH/t3dkPOCxXtOVLDQHyArwzmhhryRfoWiTc+A7LJTIcaLhiAz/3ZZA7PCvzcGZpLQ9GZrs2bBynolYGaZqwhc8ByXq15+FvoS/hLmK+kU//GcElk76RYGDAWQYW91LcHyFpAVZoMkZvB8pFD3oHIx9s4eaUC6XDk8eXKkQORqykY+yfD7jy/xnQVlSX5o+2X4bzq88NTuTwgaHGZnyVrWSfc4UM9HU8E=
