services:
    snc_second_level_cache:
        class: '%snc_redis.doctrine_cache_predis.class%'
        arguments:
            - '@snc_redis.default'

    AppBundle\Twig\:
        resource: '../../src/AppBundle/Twig'